/*
 * decompress_ps5.c  -  PS5-side zstd decompressor ELF
 *
 * Reads a manifest produced by compress_pkg.py on PC, then decompresses
 * each file to a target directory on the PS5 filesystem.
 *
 * --------------------------------------------------------------------
 * Build (OpenOrbis SDK  -  recommended for PS5 homebrew):
 *
 *   /OpenOrbis/bin/clang                   \
 *       --target x86_64-scei-ps5           \
 *       --sysroot /OpenOrbis/SDK/FreeBSD   \
 *       -I/OpenOrbis/SDK/FreeBSD/include   \
 *       -L/OpenOrbis/SDK/FreeBSD/lib       \
 *       decompress_ps5.c zstd_bundle.c     \
 *       -o decompress_ps5.elf
 *
 * Build (Linux cross-compile for FreeBSD x86_64, close enough):
 *
 *   clang --target x86_64-unknown-freebsd12 \
 *       decompress_ps5.c zstd_bundle.c       \
 *       -o decompress_ps5.elf
 *
 * zstd_bundle.c is the single-file amalgamation from the zstd project:
 *   wget https://github.com/facebook/zstd/releases/latest/download/zstd-*.tar.gz
 *   # inside: zstd/build/single_file_libs/zstd_decompress.c  <- use this
 *   cp zstd/build/single_file_libs/zstd_decompress.c zstd_bundle.c
 *
 * Or if zstd is available as a shared library on your PS5 build env:
 *   clang ... -lzstd -o decompress_ps5.elf   (drop zstd_bundle.c)
 * --------------------------------------------------------------------
 *
 * Usage on PS5 (run via kstuff payload injector / FTP shell):
 *
 *   decompress_ps5.elf <manifest.txt> <src_base> <dst_base>
 *
 * Arguments:
 *   manifest.txt  - path to the manifest.txt generated by compress_pkg.py
 *   src_base      - directory where the compressed .zst files live
 *                   (e.g. /mnt/usb0/PPSA11193-compressed)
 *   dst_base      - target directory to restore files into
 *                   (e.g. /data/game/PPSA11193-app)
 *
 * Example:
 *   decompress_ps5.elf /mnt/usb0/PPSA11193-compressed/manifest.txt \
 *                      /mnt/usb0/PPSA11193-compressed               \
 *                      /data/game/PPSA11193-app
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>

/* zstd single-file decompressor header.
 * If compiling with zstd_bundle.c, just include the header below.
 * If linking -lzstd, replace with <zstd.h> */
#include "zstd_bundle.c"    /* pulls in both header and implementation */

/* ------------------------------------------------------------------ */
#define IO_BUF     (4 * 1024 * 1024)   /* 4 MB I/O buffer              */
#define MAX_PATH   4096
#define MAX_LINE   (MAX_PATH * 2 + 64)
#define DECOMP_HEARTBEAT_SEC 10
#define DECOMP_HEARTBEAT_BYTES (256ULL * 1024ULL * 1024ULL)

typedef struct notify_request {
    char useless1[45];
    char message[3075];
} notify_request_t;

int sceKernelSendNotificationRequest(int, notify_request_t*, size_t, int);

#if defined(__linux__)
__attribute__((weak))
int sceKernelSendNotificationRequest(int a, notify_request_t *b, size_t c, int d)
{
    (void)a;
    (void)b;
    (void)c;
    (void)d;
    return -1;
}
#endif

static const char *DEFAULT_SCAN_ROOTS[] = {
    "/data/homebrew/games",
    "/user/app",
    "/mnt/ext0/user/app",
    "/data"
};

typedef struct scan_heartbeat {
    int entries_seen;
    int dirs_seen;
    int files_seen;
    int last_files_found;
    time_t last_tick;
} scan_heartbeat_t;

/* ------------------------------------------------------------------ */
static void notify_status(const char *msg)
{
    notify_request_t req;
    memset(&req, 0, sizeof(req));
    snprintf(req.message, sizeof(req.message), "%s", msg ? msg : "decompress_ps5");
    sceKernelSendNotificationRequest(0, &req, sizeof(req), 0);
}

/* ------------------------------------------------------------------ */
static void notify_progress(const char *mode, int processed, int total, int *last_bucket)
{
    if (total <= 0 || !last_bucket) {
        return;
    }

    int pct = (processed * 100) / total;
    int bucket = (pct / 10) * 10;
    if (bucket > 100) {
        bucket = 100;
    }

    while (*last_bucket + 10 <= bucket && *last_bucket < 100) {
        *last_bucket += 10;
        char nmsg[128];
        snprintf(nmsg, sizeof(nmsg), "decompress_ps5: %s %d%%", mode, *last_bucket);
        notify_status(nmsg);
    }
}

/* ------------------------------------------------------------------ */
static void notify_file_progress(const char *mode, int processed, int total)
{
    if (total <= 0) {
        return;
    }

    int pct = (processed * 100) / total;
    int prev_pct = ((processed - 1) * 100) / total;

    /* Prefer percentage-based milestones over raw file counters. */
    if (processed == 1 || processed == total || (pct / 5) > (prev_pct / 5)) {
        char nmsg[160];
        snprintf(nmsg, sizeof(nmsg), "decompress_ps5: %s %d%% (%d/%d)", mode, pct, processed, total);
        notify_status(nmsg);
    }
}

/* ------------------------------------------------------------------ */
static void heartbeat_init(scan_heartbeat_t *hb)
{
    if (!hb) {
        return;
    }
    hb->entries_seen = 0;
    hb->dirs_seen = 0;
    hb->files_seen = 0;
    hb->last_files_found = 0;
    hb->last_tick = time(NULL);
}

/* ------------------------------------------------------------------ */
static void heartbeat_tick(scan_heartbeat_t *hb, int found_count, const char *phase)
{
    if (!hb || !phase) {
        return;
    }

    hb->entries_seen++;
    if ((hb->entries_seen % 500) != 0) {
        return;
    }

    time_t now = time(NULL);
    if (hb->last_tick != 0 && (now - hb->last_tick) < 5) {
        return;
    }

    hb->last_tick = now;
    hb->last_files_found = found_count;

    char nmsg[160];
    snprintf(nmsg, sizeof(nmsg),
             "decompress_ps5: %s dirs=%d files=%d found=%d",
             phase, hb->dirs_seen, hb->files_seen, found_count);
    notify_status(nmsg);
}

/* ------------------------------------------------------------------ */
/* Recursively mkdir -p for all path components                        */
static void mkdirs(const char *path)
{
    char tmp[MAX_PATH];
    char *p;
    snprintf(tmp, sizeof(tmp), "%s", path);
    for (p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            mkdir(tmp, 0755);   /* ignore errors – dir may already exist */
            *p = '/';
        }
    }
    mkdir(tmp, 0755);
}

/* ------------------------------------------------------------------ */
/* Decompress src (.zst) -> dst                                        */
/* Returns 0 on success, -1 on error.                                  */
static int decompress_file(const char *src, const char *dst)
{
    FILE *fin  = NULL;
    FILE *fout = NULL;
    ZSTD_DCtx *dctx = NULL;
    void *ibuf = NULL;
    void *obuf = NULL;
    int   rc   = -1;

    fin = fopen(src, "rb");
    if (!fin) {
        fprintf(stderr, "  [ERR] open src failed: %s  (%s)\n", src, strerror(errno));
        goto done;
    }

    fout = fopen(dst, "wb");
    if (!fout) {
        fprintf(stderr, "  [ERR] create dst failed: %s  (%s)\n", dst, strerror(errno));
        goto done;
    }

    dctx = ZSTD_createDCtx();
    ibuf = malloc(IO_BUF);
    obuf = malloc(IO_BUF);
    if (!dctx || !ibuf || !obuf) {
        fprintf(stderr, "  [ERR] out of memory\n");
        goto done;
    }

    {
        ZSTD_inBuffer  in  = { ibuf, 0, 0 };
        size_t         n;
        long long      written = 0;
        unsigned long long read_bytes = 0;
        unsigned long long last_read_report = 0;
        time_t last_tick = time(NULL);

        while ((n = fread(ibuf, 1, IO_BUF, fin)) > 0) {
            read_bytes += (unsigned long long)n;
            in.src  = ibuf;
            in.size = n;
            in.pos  = 0;

            while (in.pos < in.size) {
                ZSTD_outBuffer out = { obuf, IO_BUF, 0 };
                size_t ret = ZSTD_decompressStream(dctx, &out, &in);
                if (ZSTD_isError(ret)) {
                    fprintf(stderr, "  [ERR] zstd: %s\n", ZSTD_getErrorName(ret));
                    goto done;
                }
                if (fwrite(obuf, 1, out.pos, fout) != out.pos) {
                    fprintf(stderr, "  [ERR] write failed: %s  (%s)\n", dst, strerror(errno));
                    goto done;
                }
                written += (long long)out.pos;
            }

            {
                time_t now = time(NULL);
                if ((read_bytes - last_read_report) >= DECOMP_HEARTBEAT_BYTES ||
                    (last_tick != 0 && (now - last_tick) >= DECOMP_HEARTBEAT_SEC)) {
                    char nmsg[192];
                    unsigned long long in_mb = read_bytes / (1024ULL * 1024ULL);
                    unsigned long long out_mb = (unsigned long long)written / (1024ULL * 1024ULL);
                    snprintf(nmsg, sizeof(nmsg),
                             "decompress_ps5: working in=%lluMB out=%lluMB",
                             in_mb, out_mb);
                    notify_status(nmsg);
                    last_read_report = read_bytes;
                    last_tick = now;
                }
            }
        }

        if (ferror(fin)) {
            fprintf(stderr, "  [ERR] read error: %s  (%s)\n", src, strerror(errno));
            goto done;
        }

        printf("  OK  (%lld bytes written)\n", written);
        rc = 0;
    }

done:
    if (dctx) ZSTD_freeDCtx(dctx);
    free(ibuf);
    free(obuf);
    if (fin)  fclose(fin);
    if (fout) fclose(fout);
    return rc;
}

/* ------------------------------------------------------------------ */
/* Strip trailing CR/LF from a string (in place)                      */
static void strip_nl(char *s)
{
    size_t len = strlen(s);
    while (len > 0 && (s[len-1] == '\n' || s[len-1] == '\r'))
        s[--len] = '\0';
}

/* ------------------------------------------------------------------ */
static int has_zst_suffix(const char *s)
{
    size_t n = strlen(s);
    if (n <= 4) {
        return 0;
    }
    const char *p = s + n - 4;
    return p[0] == '.' &&
           tolower((unsigned char)p[1]) == 'z' &&
           tolower((unsigned char)p[2]) == 's' &&
           tolower((unsigned char)p[3]) == 't';
}

/* ------------------------------------------------------------------ */
static int inplace_dst_path(const char *src_path, char *dst_path, size_t dst_cap)
{
    size_t n = strlen(src_path);
    if (!has_zst_suffix(src_path)) {
        return -1;
    }
    if (n - 4 + 1 > dst_cap) {
        return -1;
    }
    memcpy(dst_path, src_path, n - 4);
    dst_path[n - 4] = '\0';
    return 0;
}

/* ------------------------------------------------------------------ */
static void scan_count_zst(const char *root, int *count, scan_heartbeat_t *hb)
{
    DIR *dir = opendir(root);
    if (!dir) {
        fprintf(stderr, "[WARN] skip %s (%s)\n", root, strerror(errno));
        return;
    }

    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) {
            continue;
        }

        char path[MAX_PATH];
        int len = snprintf(path, sizeof(path), "%s/%s", root, ent->d_name);
        if (len < 0 || (size_t)len >= sizeof(path)) {
            continue;
        }

        struct stat st;
        if (stat(path, &st) != 0) {
            continue;
        }

        if (S_ISDIR(st.st_mode)) {
            if (hb) {
                hb->dirs_seen++;
                heartbeat_tick(hb, *count, "scanning");
            }
            scan_count_zst(path, count, hb);
            continue;
        }

        if (S_ISREG(st.st_mode) && has_zst_suffix(path)) {
            (*count)++;
        }
        if (hb && S_ISREG(st.st_mode)) {
            hb->files_seen++;
            heartbeat_tick(hb, *count, "scanning");
        }
    }

    closedir(dir);
}

/* ------------------------------------------------------------------ */
static void decompress_found_file(const char *src_path, int *ok, int *failed, int *removed)
{
    char dst_path[MAX_PATH];
    if (inplace_dst_path(src_path, dst_path, sizeof(dst_path)) != 0) {
        fprintf(stderr, "  [ERR] bad .zst path: %s\n", src_path);
        (*failed)++;
        return;
    }

    printf("  %s\n  -> %s\n", src_path, dst_path);
    if (decompress_file(src_path, dst_path) == 0) {
        (*ok)++;
        if (remove(src_path) == 0) {
            printf("  [DEL] %s\n", src_path);
            if (removed) {
                (*removed)++;
            }
        } else {
            fprintf(stderr, "  [WARN] could not delete %s (%s)\n", src_path, strerror(errno));
        }
    } else {
        (*failed)++;
    }
}

/* ------------------------------------------------------------------ */
static void scan_and_decompress(const char *root, int *listed, int *ok, int *failed,
                                int *processed, int total, int *last_bucket,
                                const char *mode, scan_heartbeat_t *hb, int *removed)
{
    DIR *dir = opendir(root);
    if (!dir) {
        fprintf(stderr, "[WARN] skip %s (%s)\n", root, strerror(errno));
        return;
    }

    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) {
            continue;
        }

        char path[MAX_PATH];
        int len = snprintf(path, sizeof(path), "%s/%s", root, ent->d_name);
        if (len < 0 || (size_t)len >= sizeof(path)) {
            fprintf(stderr, "[WARN] path too long under %s\n", root);
            continue;
        }

        struct stat st;
        if (stat(path, &st) != 0) {
            fprintf(stderr, "[WARN] stat failed: %s (%s)\n", path, strerror(errno));
            continue;
        }

        if (S_ISDIR(st.st_mode)) {
            if (hb) {
                hb->dirs_seen++;
                heartbeat_tick(hb, *processed, "decompressing");
            }
            scan_and_decompress(path, listed, ok, failed, processed,
                                total, last_bucket, mode, hb, removed);
            continue;
        }

        if (!S_ISREG(st.st_mode)) {
            continue;
        }

        if (hb) {
            hb->files_seen++;
            heartbeat_tick(hb, *processed, "decompressing");
        }

        if (!has_zst_suffix(path)) {
            continue;
        }

        (*listed)++;
        {
            int pct = (total > 0) ? ((*listed * 100) / total) : 0;
            printf("[%d%%] found .zst\n", pct);
        }
        decompress_found_file(path, ok, failed, removed);
        (*processed)++;
        notify_file_progress(mode, *processed, total);
        notify_progress(mode, *processed, total, last_bucket);
    }

    closedir(dir);
}

/* ------------------------------------------------------------------ */
static void scan_usb_mounts_count(int *count)
{
    DIR *mnt = opendir("/mnt");
    if (!mnt) {
        fprintf(stderr, "[WARN] skip /mnt (%s)\n", strerror(errno));
        return;
    }

    struct dirent *ent;
    while ((ent = readdir(mnt)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) {
            continue;
        }

        if (strncmp(ent->d_name, "usb", 3) != 0) {
            continue;
        }

        char path[MAX_PATH];
        int len = snprintf(path, sizeof(path), "/mnt/%s", ent->d_name);
        if (len < 0 || (size_t)len >= sizeof(path)) {
            continue;
        }

        struct stat st;
        if (stat(path, &st) != 0 || !S_ISDIR(st.st_mode)) {
            continue;
        }

        printf("  - %s\n", path);
        scan_count_zst(path, count, NULL);
    }

    closedir(mnt);
}

/* ------------------------------------------------------------------ */
static void scan_usb_mounts_decompress(int *listed, int *ok, int *failed,
                                       int *processed, int total,
                                       int *last_bucket, const char *mode,
                                       int *removed)
{
    DIR *mnt = opendir("/mnt");
    if (!mnt) {
        fprintf(stderr, "[WARN] skip /mnt (%s)\n", strerror(errno));
        return;
    }

    struct dirent *ent;
    while ((ent = readdir(mnt)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) {
            continue;
        }

        if (strncmp(ent->d_name, "usb", 3) != 0) {
            continue;
        }

        char path[MAX_PATH];
        int len = snprintf(path, sizeof(path), "/mnt/%s", ent->d_name);
        if (len < 0 || (size_t)len >= sizeof(path)) {
            continue;
        }

        struct stat st;
        if (stat(path, &st) != 0 || !S_ISDIR(st.st_mode)) {
            continue;
        }

        printf("  - %s\n", path);
        scan_and_decompress(path, listed, ok, failed, processed,
                    total, last_bucket, mode, NULL, removed);
    }

    closedir(mnt);
}

/* ------------------------------------------------------------------ */
static int run_manifest_mode(const char *manifest_path, const char *src_base, const char *dst_base)
{
    char nmsg[256];
    printf("decompress_ps5  -  manifest mode\n");
    printf("  Manifest : %s\n", manifest_path);
    printf("  Src base : %s\n", src_base);
    printf("  Dst base : %s\n", dst_base);
    printf("--------------------------------------------\n");
    notify_status("decompress_ps5: started (manifest mode)");

    FILE *mf_count = fopen(manifest_path, "r");
    if (!mf_count) {
        fprintf(stderr, "Cannot open manifest: %s  (%s)\n", manifest_path, strerror(errno));
        return 1;
    }

    int total = 0;
    char line[MAX_LINE];
    while (fgets(line, sizeof(line), mf_count)) {
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r') {
            continue;
        }
        total++;
    }
    fclose(mf_count);

    snprintf(nmsg, sizeof(nmsg), "decompress_ps5: manifest entries=%d", total);
    notify_status(nmsg);

    FILE *mf = fopen(manifest_path, "r");
    if (!mf) {
        fprintf(stderr, "Cannot open manifest: %s  (%s)\n", manifest_path, strerror(errno));
        return 1;
    }

    int ok = 0, failed = 0, processed = 0, removed = 0;
    int last_bucket = 0;

    while (fgets(line, sizeof(line), mf)) {
        /* Skip comments (start with #) and blank lines */
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r')
            continue;

        strip_nl(line);

        /* Parse pipe-delimited fields:  src_rel | dst_rel | orig_size | comp_size */
        char *saveptr  = NULL;
        char *src_rel  = strtok_r(line,  "|", &saveptr);
        char *dst_rel  = strtok_r(NULL,  "|", &saveptr);
        char *orig_str = strtok_r(NULL,  "|", &saveptr);   /* may be NULL */

        if (!src_rel || !dst_rel) continue;   /* malformed line */

        long long orig_size = orig_str ? atoll(orig_str) : 0;

        /* Build full paths */
        char src_path[MAX_PATH], dst_path[MAX_PATH], dst_dir[MAX_PATH];

        /* Normalise any backslashes from Windows-side path in manifest */
        for (char *c = src_rel; *c; c++) if (*c == '\\') *c = '/';
        for (char *c = dst_rel; *c; c++) if (*c == '\\') *c = '/';

        snprintf(src_path, sizeof(src_path), "%s/%s", src_base, src_rel);
        snprintf(dst_path, sizeof(dst_path), "%s/%s", dst_base, dst_rel);

        /* Create parent directories for the destination file */
        snprintf(dst_dir, sizeof(dst_dir), "%s", dst_path);
        char *slash = strrchr(dst_dir, '/');
        if (slash) {
            *slash = '\0';
            mkdirs(dst_dir);
        }

        {
            int pct = (total > 0) ? (((processed + 1) * 100) / total) : 0;
            printf("[%d%%] %s\n    -> %s  (%lld bytes)\n",
                   pct, src_rel, dst_path, orig_size);
        }

        if (decompress_file(src_path, dst_path) == 0) {
            ok++;
            if (remove(src_path) == 0) {
                removed++;
                printf("  [DEL] %s\n", src_path);
            } else {
                fprintf(stderr, "  [WARN] could not delete %s (%s)\n", src_path, strerror(errno));
            }
        } else {
            failed++;
        }

        processed++;
        notify_file_progress("manifest", processed, total);
        notify_progress("manifest", processed, total, &last_bucket);
    }

    fclose(mf);

    printf("--------------------------------------------\n");
    notify_progress("manifest", total, total, &last_bucket);
    printf("Done: %d OK,  %d failed,  %d removed,  %d total\n", ok, failed, removed, processed);
    snprintf(nmsg, sizeof(nmsg),
             "decompress_ps5: COMPLETE 100%% (manifest) ok=%d fail=%d removed=%d total=%d",
             ok, failed, removed, processed);
    notify_status(nmsg);

    return failed > 0 ? 1 : 0;
}

/* ------------------------------------------------------------------ */
static int run_auto_mode(int root_count, char **roots)
{
    int total = 0;
    int listed = 0;
    int processed = 0;
    int ok = 0;
    int failed = 0;
    int removed = 0;
    int last_bucket = 0;
    scan_heartbeat_t hb;
    char nmsg[256];

    heartbeat_init(&hb);

    printf("decompress_ps5  -  auto mode\n");
    notify_status("decompress_ps5: started (auto mode)");
    if (root_count == 0) {
        printf("  Roots: defaults\n");
        for (size_t i = 0; i < sizeof(DEFAULT_SCAN_ROOTS) / sizeof(DEFAULT_SCAN_ROOTS[0]); i++) {
            printf("  - %s\n", DEFAULT_SCAN_ROOTS[i]);
        }
        printf("  - /mnt/usb* (auto-detected)\n");
        printf("--------------------------------------------\n");
        notify_status("decompress_ps5: scanning defaults for .zst (this can take time)");
        for (size_t i = 0; i < sizeof(DEFAULT_SCAN_ROOTS) / sizeof(DEFAULT_SCAN_ROOTS[0]); i++) {
            printf("[SCAN] %s\n", DEFAULT_SCAN_ROOTS[i]);
            snprintf(nmsg, sizeof(nmsg), "decompress_ps5: scanning %s", DEFAULT_SCAN_ROOTS[i]);
            notify_status(nmsg);
            scan_count_zst(DEFAULT_SCAN_ROOTS[i], &total, &hb);
        }
        scan_usb_mounts_count(&total);

        printf("  Total .zst found: %d\n", total);
        snprintf(nmsg, sizeof(nmsg), "decompress_ps5: found %d .zst", total);
        notify_status(nmsg);
        if (total > 0) {
            heartbeat_init(&hb);
            for (size_t i = 0; i < sizeof(DEFAULT_SCAN_ROOTS) / sizeof(DEFAULT_SCAN_ROOTS[0]); i++) {
                printf("[DECOMP] %s\n", DEFAULT_SCAN_ROOTS[i]);
                scan_and_decompress(DEFAULT_SCAN_ROOTS[i], &listed, &ok, &failed,
                                                &processed, total, &last_bucket, "auto", &hb, &removed);
            }
            scan_usb_mounts_decompress(&listed, &ok, &failed,
                                                    &processed, total, &last_bucket, "auto", &removed);
        }
    } else {
        printf("  Roots:\n");
        for (int i = 0; i < root_count; i++) {
            printf("  - %s\n", roots[i]);
        }
        printf("--------------------------------------------\n");
        notify_status("decompress_ps5: scanning custom roots for .zst");
        for (int i = 0; i < root_count; i++) {
            printf("[SCAN] %s\n", roots[i]);
            snprintf(nmsg, sizeof(nmsg), "decompress_ps5: scanning %s", roots[i]);
            notify_status(nmsg);
            scan_count_zst(roots[i], &total, &hb);
        }

        printf("  Total .zst found: %d\n", total);
        snprintf(nmsg, sizeof(nmsg), "decompress_ps5: found %d .zst", total);
        notify_status(nmsg);
        if (total > 0) {
            heartbeat_init(&hb);
            for (int i = 0; i < root_count; i++) {
                printf("[DECOMP] %s\n", roots[i]);
                scan_and_decompress(roots[i], &listed, &ok, &failed,
                                    &processed, total, &last_bucket, "auto", &hb, &removed);
            }
        }
    }

    if (total == 0) {
        notify_status("decompress_ps5: no .zst found (check path/mount)");
    }

    printf("--------------------------------------------\n");
    notify_progress("auto", total, total, &last_bucket);
    printf("Done: %d OK,  %d failed,  %d removed,  %d total .zst\n", ok, failed, removed, processed);
    snprintf(nmsg, sizeof(nmsg),
             "decompress_ps5: COMPLETE 100%% (auto) ok=%d fail=%d removed=%d total=%d",
             ok, failed, removed, processed);
    notify_status(nmsg);
    return failed > 0 ? 1 : 0;
}

/* ------------------------------------------------------------------ */
int main(int argc, char *argv[])
{
    if (argc <= 1) {
        return run_auto_mode(0, NULL);
    }

    if (argc >= 2 && strcmp(argv[1], "--auto") == 0) {
        return run_auto_mode(argc - 2, &argv[2]);
    }

    if (argc < 4) {
        fprintf(stderr,
            "Usage:\n"
            "  %s <manifest.txt> <src_base> <dst_base>\n"
            "  %s --auto [scan_root1] [scan_root2] ...\n"
            "\n"
            "Manifest mode:\n"
            "  manifest.txt  generated by compress_pkg.py on PC\n"
            "  src_base      folder containing the .zst files\n"
            "  dst_base      target folder to restore files into\n"
            "\n"
            "Auto mode:\n"
            "  recursively scans roots for .zst files and decompresses in place\n"
            "  if no roots are provided, defaults are:\n"
            "    /data/homebrew/games, /user/app, /mnt/ext0/user/app, /data\n"
            "    plus any mounted /mnt/usb* paths\n",
            argv[0], argv[0]);
        return 1;
    }

    return run_manifest_mode(argv[1], argv[2], argv[3]);
}
